[package]
name = "string_sum"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

[lib]
name = "string_sum"
crate-type = ["cdylib"]

[dependencies]
pyo3-ffi = { path = "../../" }

[build-dependencies]
pyo3-build-config = { path = "../../../pyo3-build-config" }

[workspace]
