[package]
authors = ["{{authors}}"]
name = "{{project-name}}"
version = "0.1.0"
edition = "2018"

[lib]
name = "word_count"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "{{PYO3_VERSION}}", features = ["native-module"] }
rayon = "1.0.2"
