[package]
authors = ["{{authors}}"]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[lib]
name = "word_count"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "{{PYO3_VERSION}}"
rayon = "1.0.2"
