[package]
name = "xtask"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "xtask"

[dependencies]
anyhow = "1.0.51"

# Clap 3 requires MSRV 1.54
rustversion = "1.0"
structopt = { version = "0.3", default-features = false }
clap = { version = "2" }
