blank_issues_enabled: true
contact_links:
  - name: â“ Question
    url: https://github.com/PyO3/pyo3/discussions
    about: Ask and answer questions about PyO3 on Discussions
  - name: ğŸ”§ Troubleshooting
    url: https://github.com/PyO3/pyo3/discussions
    about: For troubleshooting help, see the Discussions
  - name: ğŸ‘‹ Chat
    url: https://discord.gg/33kcChzH7f
    about: Engage with PyO3's users and developers on Discord
