[package]
name = "word-count"
version = "0.1.0"
edition = "2018"

[lib]
name = "word_count"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { path = "../..", features = ["native-module"] }
rayon = "1.0.2"

[workspace]
