[package]
name = "pyo3cls"
version = "0.2.5"
description = "Proc macros for PyO3 package"
authors = ["PyO3 Project and Contributors <https://github.com/PyO3"]
homepage = "https://github.com/pyo3/pyo3"
repository = "https://github.com/pyo3/pyo3.git"
documentation = "http://pyo3.github.io/PyO3/pyo3/"
categories = ["api-bindings", "development-tools::ffi"]
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote="0.5"

[dependencies.syn]
version="0.13"
features=["full", "parsing", "printing", "extra-traits"]


[dependencies.pyo3-derive-backend]
path = "../pyo3-derive-backend"
version = "0.2.5"
