[package]
name = "pyo3-examples"
version = "0.0.0"
publish = false
edition = "2021"
rust-version = "1.83"

[dev-dependencies]
pyo3 = { path = "..", features = ["auto-initialize"] }

[[example]]
name = "decorator"
path = "decorator/src/lib.rs"
crate-type = ["cdylib"]
doc-scrape-examples = true
