[package]
name = "pyo3-examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
pyo3 = { path = "..", features = ["auto-initialize", "extension-module"] }

[[example]]
name = "decorator"
path = "decorator/src/lib.rs"
crate_type = ["cdylib"]
doc-scrape-examples = true
