[package]
name = "decorator"
version = "0.1.0"
edition = "2018"

[lib]
name = "decorator"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { path = "../../", features = ["extension-module"] }

[features]
pep489 = ["pyo3/pep489"]

[workspace]
