[package]
name = "setuptools-rust-starter"
version = "0.1.0"
edition = "2021"

[lib]
name = "setuptools_rust_starter"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { path = "../../", features = ["extension-module"] }

[workspace]
