name: benches

on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}-benches
  cancel-in-progress: true

env:
  UV_PYTHON: "3.14t"

jobs:
  benchmarks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7
        with:
          # codspeed action needs to be run from within the final Python environment
          activate-environment: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            .
            pyo3-benches
          save-if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'CI-save-pr-cache') }}
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          run: uvx nox -s codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: simulation
