name: changelog

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, edited]

jobs:
  check:
    name: Check changelog entry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: python -m pip install --upgrade pip && pip install nox[uv]
      - run: nox -s check-changelog
